### PR TITLE
My edits1

### PR DESCRIPTION
**Pull request by CallumMcFadgen**

### CODE REVIEW

**Comment by MatthiasStudent** [comment]
Hi Callum, looks like your working off the original copy of the Tutorial?  Have you forked it first to your own repository?  I'm not versed enough with GitHub to show you how to save (push) your committed changes to an online repo in your account, need to ask Ali ;-)

**Comment by CallumMcFadgen** [comment]
Hi Matthias,Ah I wondered about that, I think accidently sent you a pull request to the original repo when I was pushing the “MyEdit1” branch to my repo. Sorry about that.  I definitely have a forked repo in my own Github and a cloned copy on my local directory so I think you should just close the pull request and my work in my forked and local repos should be fine 😊 Thanks,Callum From: MatthiasStudentSent: 02 March 2020 03:46:PMTo: NMIT-SDV701/ClassTutorial1Cc: Callum McFadgen; State changeSubject: Re: [NMIT-SDV701/ClassTutorial1] My edits1 (#5) Hi Callum, looks like your working off the original copy of the Tutorial? Have you forked it first to your own repository? I'm not versed enough with GitHub to show you how to save (push) your committed changes to an online repo in your account, need to ask Ali ;-)—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com

**Comment by MatthiasStudent** [comment]
Yes, I see it's closed, so no problem at my end.  I just wonder how it ended up the SDV701 repo, and how one can decide in VS which repo to push to, or how to send a Pull Request from VS.
I'm just not using GitHub enough to be fluent.

**Comment by CallumMcFadgen** [comment]
git commit							//saves changes to the branch

git checkout [branch name]			//work in that branch

git checkout -b [branch name]		//puts the user on a new branch

git create branch [branch name]		//creates a new branch

git merge [branch name]				//merges two branches together (the branch name should be the branch you are working on, ie merging this branch to the master branch)

git status							//displays the status of the branch

git log 							//displays all commits

git log --oneline					//shortened version of log (easier to read)

git add .							//save changes

git commit -m "[message]"			//saves changes to the branch with a message

git push origin [branch name]		//updates the server (the branch name should be the branch you are working on, ie merging this branch to the master branch)

git branch -d [branch name]			//deletes the specified branch

git branch							//shows branches (local)

git branch -a 						//shows all branches (local and server)

git pull 							//gets update from server

git pull orign [branch name] 		//gets update from a specific branch

git init							//initilizes an existing directory into a Git Repo

git clone [repo URL]				//retrive an existing repo from a host URL

**Pull request closed without merging**
